 
function uart_tx6_config(this_block)

  % Revision History:
  %
  %   09-Dec-2013  (13:46 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\SysGenWork\Picoblaze\uart_tx6_CE.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('uart_tx6');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('data_in');
  this_block.addSimulinkInport('en_16_x_baud');
  this_block.addSimulinkInport('buffer_write');
  this_block.addSimulinkInport('buffer_reset');

  this_block.addSimulinkOutport('serial_out');
  this_block.addSimulinkOutport('buffer_data_present');
  this_block.addSimulinkOutport('buffer_half_full');
  this_block.addSimulinkOutport('buffer_full');

  serial_out_port = this_block.port('serial_out');
  serial_out_port.setType('UFix_1_0');
  serial_out_port.useHDLVector(false);
  buffer_data_present_port = this_block.port('buffer_data_present');
  buffer_data_present_port.setType('UFix_1_0');
  buffer_data_present_port.useHDLVector(false);
  buffer_half_full_port = this_block.port('buffer_half_full');
  buffer_half_full_port.setType('UFix_1_0');
  buffer_half_full_port.useHDLVector(false);
  buffer_full_port = this_block.port('buffer_full');
  buffer_full_port.setType('UFix_1_0');
  buffer_full_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('data_in').width ~= 8);
      this_block.setError('Input data type for port "data_in" must have width=8.');
    end

    if (this_block.port('en_16_x_baud').width ~= 1);
      this_block.setError('Input data type for port "en_16_x_baud" must have width=1.');
    end

    this_block.port('en_16_x_baud').useHDLVector(false);

    if (this_block.port('buffer_write').width ~= 1);
      this_block.setError('Input data type for port "buffer_write" must have width=1.');
    end

    this_block.port('buffer_write').useHDLVector(false);

    if (this_block.port('buffer_reset').width ~= 1);
      this_block.setError('Input data type for port "buffer_reset" must have width=1.');
    end

    this_block.port('buffer_reset').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'clk','ce')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('../../Picoblaze/uart_tx6_CE.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

